### ISSUE TITLE
Invalid title.tmd with WiiVC injector

### ISSUE THREAD

**Issue by magomagal** [V10lator/NUSspli#267] opened 2024-01-17 15:14 UTC
I get the "Invalid title.tmd file!" error when trying to install an injected WiiVC title using piratesephiroth's fork of TeconmoonWiiVCInjector, I'm using the default options and everything on the application seems fine, It doesn't give me any errors.
Any ideas?
I'm using the latest release on Tiramisu via homebrew channel in case that information matters.

**Comment by V10lator** [comment] 2024-01-17 15:41
Can you send me one of the failing title.tmd files, please? Also make sure you're using the newest version of Teconmoon's Injector: https://github.com/piratesephiroth/TeconmoonWiiVCInjector/releases/latest

**Comment by magomagal** [comment] 2024-01-17 15:47
Github won't let me upload it directly so did it via Google Drive, here you go: https://drive.google.com/file/d/1eU2dvwx460eQuCmJJVjvGEhr9jmrP0Cm/view?usp=sharing
I checked just in case, and I'm using the latest version of the Injector.

**Comment by V10lator** [comment] 2024-01-17 16:16
Looked at the file in a hex editor a bit confirming offsets and a few other stuff and for me it looks good.

Now I can't use my Wii U at the moment. So if you want to do me a big flavor / speed the debugging process up: Could you deinstall the NUSspli version you're currently using and replace it with a DEBUG build? Download and run https://github.com/dimok789/loadiine_gx2/raw/master/udp_debug_reader/UdpDebugReader.exe on your PC. Make sure there's no firewall or something blocking connections between PC and Wii U. Now start the DEBUG version of NUSspli and try to install the faulty inject again. This should produce a log in that window from UdpDebugReader on your PC. When you see the red error screen on the Wii U that's enough, just copy and paste the log then.

**Comment by magomagal** [comment] 2024-01-17 16:23
Sure, I'll try it and post results

**Comment by magomagal** [comment] 2024-01-17 16:25
Wed 17 Jan 2024 01:48:25.746    main: 0x00000B78/0x0000FFF8
Wed 17 Jan 2024 01:48:25.934    SDL initialized!
Wed 17 Jan 2024 01:48:25.945    Changed main thread priority!
Wed 17 Jan 2024 01:48:25.963    Crypto initialized!
Wed 17 Jan 2024 01:48:25.980    MCP initialized!
Wed 17 Jan 2024 01:48:26.102    Sanity checked!
Wed 17 Jan 2024 01:48:26.125    Notification system initialized!
Wed 17 Jan 2024 01:48:26.157    Downloader initialized!
Wed 17 Jan 2024 01:48:26.216    Initializing config file...
Wed 17 Jan 2024 01:48:26.221    System language found: Portuguese
Wed 17 Jan 2024 01:48:26.229    Config file loaded!
Wed 17 Jan 2024 01:48:26.229    Config loaded!
Wed 17 Jan 2024 01:48:26.263    SWKBD_Init()
Wed 17 Jan 2024 01:48:26.639    main(): Checking thread stacks...
Wed 17 Jan 2024 01:48:26.640    main(): 0x00004970/0x0000FFF8
Wed 17 Jan 2024 01:48:26.640    Download URL: https://napi.nbg01.v10lator.de/v2/s?t=a
Wed 17 Jan 2024 01:48:26.641    Download PATH: <RAM>
Wed 17 Jan 2024 01:48:26.641    Calling curl_easy_perform()
Wed 17 Jan 2024 01:48:26.642    Download thread spawned!
Wed 17 Jan 2024 01:48:27.692    STACK: NUSspli downloader: 0x00003C10/0x00008000
Wed 17 Jan 2024 01:48:27.692    curl_easy_perform() returned: 0
Wed 17 Jan 2024 01:48:27.693    curl_easy_perform executed successfully
Wed 17 Jan 2024 01:48:27.694    Download JSON finished!
Wed 17 Jan 2024 01:48:27.742    Newest version!
Wed 17 Jan 2024 01:48:27.742    main: Checking thread stacks...
Wed 17 Jan 2024 01:48:27.745    main: 0x00004970/0x0000FFF8
Wed 17 Jan 2024 01:48:38.287    STACK: NUSspli FS Initialiser: 0x00000200/0x00000400
Wed 17 Jan 2024 01:48:39.435    Teconmoon title.tmd file detected, fixing...
Wed 17 Jan 2024 01:48:39.436    Invalid title.tmd file (content: 15, size: 0)

**Comment by V10lator** [comment] 2024-01-17 16:37
No need for UWU logs, something strange is going on here. Now just ignore what I just wrote, this is for @piratesephiroth :

The TMD hashes are all zeros, wasn't that fixed like two years ago? Also it says one of the .app files has a filesize of 0 which doesn't make much sense.

Just to make sure @magomagal is there really an .app file with a filesize of 0 bytes? Also could you maybe hop onto our Discord ( https://discord.gg/B8ZBd6mrnV ) and DM me the whole inject (as a zip file or something) there?

**Comment by magomagal** [comment] 2024-01-17 16:43
There aren't any .app files with 0 bytes, only .h3 files with 0 bytes, which I assume isn't really the same thing.
I'll just have some lunch and then I'll hop on discord

**Comment by V10lator** [comment] 2024-01-17 16:45
(tech bla: The line `Teconmoon title.tmd file detected, fixing...` from the logs shows empty hashes (also confirmed with a hex editor). NUSspli fixes the hashes when it detects this (it also calls it `Teconmoon title.tmd file` as this was a bug there around two years ago - there seems to be a regression now) but the fixed ticket also fails the sanity check as NUSspli assumes .app files with a filesize of 0 don't exist (16. content entry in the tmd file. NUSspli just says 15 cause the index starts at 0, not at 1)).

> There aren't any .app files with 0 bytes

Thanks for confirming. I suspected this to be a mistake already, just wanted to get sure. :)

> only .h3 files with 0 bytes, which I assume isn't really the same thing.

This somehow sounds weird but yea, .h3 files are a different thing.

**Comment by V10lator** [comment] 2024-01-17 16:48
With there don't beeing a 0 byte .app file I'll close this bug now through. Simply because it's not a bug in NUSspli but in Teconmoon's Injector.

See you on Discord soon. :)

**Closed by V10lator** 2024-01-17 16:48 UTC
Labels: invalid

**Comment by magomagal** [comment] 2024-01-17 17:11
Sent you a DM
