### ISSUE TITLE
SSL Error update

### ISSUE THREAD

**Issue by dinowars007** [V10lator/NUSspli#297] opened 2024-03-31 23:36 UTC
When trying to update from v1.144 to v1.149 it said SSL Error and told me to ensure my wii u time and date is correct which is the case, when manually updated to that version. Also happens when it tries to do it update check on the latest version.

**Comment by V10lator** [comment] 2024-04-01 08:25
Duplicate of #285

**Closed by V10lator** 2024-04-01 08:25 UTC
Labels: duplicate, invalid
