### ISSUE TITLE
SSL error, Nusspli v1.144 wont update, telling me to check date and time but I already did

### ISSUE THREAD

**Issue by Cupidangel7** [V10lator/NUSspli#320] opened 2024-06-17 00:10 UTC
I've never used GitHub before, so I'm super sorry if this isn't the right place to put this!!
I haven't touched my Wii U in a while, like last time maybe was December 2023? So I'm not sure if this problem was caused because of inactivity on my end..
But anyway whenever I open nusspli it opens up with a update screen to update to 1.151 but update fails each time and tells me to check time and date, but the time and date are correct so I'm not sure.
And also gives me a error screen saying "error downloading https://(github 1.151 download)" after I press out. 

If anyone knows how to fix this I'll be super grateful!!

**Comment by V10lator** [comment] 2024-06-17 10:27
Normally I would just close this as duplicate but

> I've never used GitHub before, so I'm super sorry if this isn't the right place to put this!!

So let me explain: GitHub did a change at its SSL certificates which broke NUSsplis SSL validation. So the update check to my server still works but trying to download the update file from GitHub won't work anymore.
Beside that there was a small issue on my end in older NUSspli versions which disallows to continue normal operation from this screen error.

To update now you have to grab the latest release from https://github.com/V10lator/NUSspli/releases/latest and piut the files on your SD card.
There's a special case through: You might notice that there is no HBL version anymore so in case this is what you use now on 1.144 you'll need to switch to another version.

Now closing this as duplicate of #285 ... ;)

**Closed by V10lator** 2024-06-17 10:27 UTC
Labels: duplicate, invalid

**Comment by V10lator** [comment] 2024-06-17 10:36
Oh and if you have more question hop to our Discord ( https://discord.gg/B8ZBd6mrnV ) or GBATemp thread ( https://gbatemp.net/threads/nusspli-install-content-directly-from-the-nintendo-update-servers-to-your-wii-u.566055/ ), please.
