### ISSUE TITLE
Fature request: list & erase downloaded packages (Keep downloaded files: YES)

### ISSUE THREAD

**Issue by Maxximo88** [V10lator/NUSspli#315] opened 2024-05-24 12:20 UTC
Hi,
In case a user decide to install a contend with the following setting:
**Keep downloaded files: YES**
Is it possible to add the feature to show the LIST of "Downloaded files" and allow the user to ERASE it?
Maybe also with a "Erase all" option?

Thanks for your amazing work!

**Comment by V10lator** [comment] 2024-05-24 15:05
Duplicate of #271

**Closed by V10lator** 2024-05-24 15:05 UTC
Labels: duplicate
