### ISSUE TITLE
Update to 1.149 SSL error

### ISSUE THREAD

**Issue by Supafly187** [V10lator/NUSspli#305] opened 2024-04-16 16:43 UTC
"Check your Wii Us date and time settings"

I can still use v1.444 but I'd like to update to the newest version, I've manually updated the date and time in the Wii U settings, and I've connected to the internet to automatically do it but no luck.

**Comment by V10lator** [comment] 2024-04-16 16:46
Duplicate of #285

**Closed by V10lator** 2024-04-16 16:46 UTC
Labels: duplicate, invalid
